#!/usr/bin/bash

pushd /opt/seafile/conf
sed "s#<SEAFILE_SERVICE_URL>#${SEAFILE_SERVICE_URL:-http://127.0.0.1}#g" -i ccnet.conf
sed "s#<SEAFILE_HUB_WORKERS>#${SEAFILE_HUB_WORKERS:-5}#g" -i gunicorn.conf.py
sed "s#<SEAFILE_HUB_PORT>#${SEAFILE_HUB_PORT:-8000}#g" -i gunicorn.conf.py
sed "s#<SEAFILE_WEBDAV_ENABLED>#${SEAFILE_WEBDAV_ENABLED:-false}#g" -i seafdav.conf
sed "s#<SEAFILE_WEBDAV_HOST>#${SEAFILE_WEBDAV_HOST:-0.0.0.0}#g" -i seafdav.conf
sed "s#<SEAFILE_WEBDAV_FASTCGI>#${SEAFILE_WEBDAV_FASTCGI:-false}#g" -i seafdav.conf
sed "s#<SEAFILE_WEBDAV_PORT>#${SEAFILE_WEBDAV_PORT:-8080}#g" -i seafdav.conf
sed "s#<SEAFILE_WEBDAV_SHARE_NAME>#${SEAFILE_WEBDAV_SHARE_NAME:-/}#g" -i seafdav.conf
sed "s#<SEAFILE_FILESERVER_PORT>#${SEAFILE_FILESERVER_PORT:-8082}#g" -i seafile.conf
popd

seafile.sh start
seahub.sh start $SEAFILE_HUB_PORT
